force-app/main/default/objects/Lead/fields/Medicare_Number__c.field-meta.xml
<CustomField>
    <fullName>Medicare_Number__c</fullName>
    <label>Medicare Number</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Patient_Medicare_Number__c.field-meta.xml
<CustomField>
    <fullName>Patient_Medicare_Number__c</fullName>
    <label>Patient Medicare Number</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Patient__c/Patient__c.object-meta.xml
<CustomObject>
    <label>Patient</label>
    <nameField>
        <label>Patient Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Patients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Patient__c/fields/Medicare_Number__c.field-meta.xml
<CustomField>
    <fullName>Medicare_Number__c</fullName>
    <label>Medicare Number</label>
    <length>16</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Provider__c/Provider__c.object-meta.xml
<CustomObject>
    <label>Provider</label>
    <nameField>
        <label>Provider Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Providers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/LeadControllerExtension.cls
public class LeadControllerExtension {

    public Boolean PatientExists {get; set;}
    public Boolean PatientDoesNotExist {get; set;}
    private PageReference returnPage;
    public Lead lead {get; set;}
    public Provider__c provider {get; set;}

    public LeadControllerExtension(ApexPages.StandardController controller) {

        returnPage = controller.view();
        Id leadId = ApexPages.currentPage().getParameters().get('id');
        
        //TODO: Query for all of the sObjects we need here
        lead = GetLead(leadId);
        Patient__c patient = GetPatient(lead.Patient_Medicare_Number__c);

        PatientExists = (patient == null);
        PatientDoesNotExist = !PatientExists;
    }

    public PageReference DoConvert() {
        returnPage.setRedirect(true);
        return returnPage;
    }    

    private static Lead GetLead(Id leadId) {
        return [SELECT Id, Patient_Medicare_Number__c FROM Lead WHERE Id = :leadId];
    }

    private static Patient__c GetPatient(String medicareNumber) {
        return [SELECT Id, Name FROM Patient__c WHERE Medicare_Number__c = :medicareNumber];        
    }
}