force-app/main/default/objects/Contact/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Medicare_Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Medicare_Expiration_Date__c</fullName>
    <label>Medicare Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Medicare_Number__c.field-meta.xml
<CustomField>
    <fullName>Medicare_Number__c</fullName>
    <label>Medicare Number</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Medicare_Referral_Number__c.field-meta.xml
<CustomField>
    <fullName>Medicare_Referral_Number__c</fullName>
    <label>Medicare Referral Number</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Patient_Phone__c.field-meta.xml
<CustomField>
    <fullName>Patient_Phone__c</fullName>
    <label>Patient Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Provider_Number__c.field-meta.xml
<CustomField>
    <fullName>Provider_Number__c</fullName>
    <label>Provider Number</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Referral_Reason__c.field-meta.xml
<CustomField>
    <fullName>Referral_Reason__c</fullName>
    <label>Referral Reason</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <label>Service</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Service</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sleep_Referral__c/Sleep_Referral__c.object-meta.xml
<CustomObject>
    <label>Sleep Referral</label>
    <nameField>
        <label>Sleep Referral Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sleep Referrals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sleep_Referral__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sleep Referrals</relationshipLabel>
    <relationshipName>Sleep_Referrals</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sleep_Referral__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Sleep Referrals</relationshipLabel>
    <relationshipName>Sleep_Referrals</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sleep_Referral__c/fields/Created_from_Lead__c.field-meta.xml
<CustomField>
    <fullName>Created_from_Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Created from Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Sleep Referrals</relationshipLabel>
    <relationshipName>Sleep_Referrals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sleep_Referral__c/fields/Medicare_Referral_Number__c.field-meta.xml
<CustomField>
    <fullName>Medicare_Referral_Number__c</fullName>
    <label>Medicare Referral Number</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sleep_Referral__c/fields/Referral_Reason__c.field-meta.xml
<CustomField>
    <fullName>Referral_Reason__c</fullName>
    <label>Referral Reason</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sleep_Referral__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <label>Service</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Service</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Service.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Medicare-funded sleep study</fullName>
    </customValue>
    <customValue>
        <fullName>Physician Consult (NSW only)</fullName>
    </customValue>
    <customValue>
        <fullName>Patient-funded sleep study</fullName>
    </customValue>
    <customValue>
        <fullName>CPAP treatment</fullName>
    </customValue>
    <masterLabel>Service</masterLabel>
</GlobalValueSet>

force-app/main/default/tests/LeadConversionTests.cls
@IsTest
public class LeadConversionTests {

    @IsTest static void CanConvertLead() {

        Lead lead = new Lead();
        lead.Company = 'Dr. John Williams';
        lead.Date_of_Birth__c = Date.today().addYears(-25);
        lead.Email = 'someTest@mitchroutt.com';
        lead.Fax = '+1(576)999-9994';
        lead.Gender__c = 'Male';
        lead.Medicare_Number__c = '9993844AFDS';
        lead.Medicare_Expiration_Date__c = Date.today().addYears(1);
        lead.FirstName = 'Tom';
        lead.LastName = 'Jones';
        lead.Provider_Number__c = 'AAFFFF99989';
        lead.Referral_Reason__c = 'Trouble Sleeping';
        lead.Medicare_Referral_Number__c = 'REW4452';
        lead.Service__c = 'Medicare-funded sleep study';
        lead.Phone = '+1(444)847-0909';

        insert lead;

        // Validate the account was created
        List<Account> accounts = [SELECT Id, Name, Phone, Fax FROM Account WHERE Provider_Number__c = :lead.Provider_Number__c AND Email__c = :lead.Email]; 
        System.assertEquals(1, accounts.size());
        Account account = accounts.get(0);
        System.assertEquals(lead.Company, account.Name);
        System.assertEquals(lead.Fax, account.Fax);
        System.assertEquals(lead.Phone, account.Phone);
        
        // Validate the associated contact was created
        List<Contact> contacts = [SELECT Id, AccountId, FirstName, LastName, Phone, Medicare_Number__c, Medicare_Expiration_Date__c, Gender__c, Language__c, Birthdate FROM Contact];
        System.assertEquals(1, contacts.size());
        Contact contact = contacts.get(0);
        System.assertEquals(account.Id, contact.AccountId);
        System.assertEquals(lead.Medicare_Number__c, contact.Medicare_Number__c);
        System.assertEquals(lead.FirstName, contact.FirstName);
        System.assertEquals(lead.LastName, contact.LastName);
        System.assertEquals(lead.Patient_Phone__c, contact.Phone);
        System.assertEquals(lead.Medicare_Expiration_Date__c, contact.Medicare_Expiration_Date__c);
        System.assertEquals(lead.Gender__c, contact.Gender__c);
        System.assertEquals(lead.Language__C, contact.Language__c);
        System.assertEquals(lead.Date_of_Birth__c, contact.Birthdate);

        // Validate that the sleep referral was created
        List<Sleep_Referral__c> sleepReferrals = [SELECT Id, Account__c, Contact__c, Created_from_Lead__c, Referral_Reason__c, Medicare_Referral_Number__c FROM Sleep_Referral__c];
        System.assertEquals(1, sleepReferrals.size());
        Sleep_Referral__c sleepReferral = sleepReferrals.get(0);
        System.assertEquals(account.Id, sleepReferral.Account__c);
        System.assertEquals(contact.Id, sleepReferral.Contact__c);
        System.assertEquals(lead.Id, sleepReferral.Created_from_Lead__c);
        System.assertEquals(lead.Medicare_Referral_Number__c, sleepReferral.Medicare_Referral_Number__c);
        System.assertEquals(lead.Referral_Reason__c, sleepReferral.Referral_Reason__c);

        // Validate that an email was sent
        Integer emailInvocations = Limits.getEmailInvocations();
        System.assertEquals(1, emailInvocations);
    }
}